scss_files: 'source/stylesheets/*.css.scss'
exclude: 'source/stylesheets/_normalize.scss'

linters:
  ColorKeyword:
    enabled: false

  ColorVariable:
    enabled: false

  HexLength:
    enabled: true
    style: long

  HexNotation:
    enabled: true
    style: uppercase

  Shorthand:
    enabled: false
